version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 2
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: codeceptjs
    versions:
    - 3.0.4
  - dependency-name: node-notifier
    versions:
    - 8.0.1
